services:
  - type: web
    name: veritensor-api
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SIMULATION_MODE
        value: "true"
      - key: SEED_TASKS
        value: "160"
      - key: SEED_MINERS
        value: "14"
      - key: SEED_VALIDATORS
        value: "4"
      - key: CORS_ORIGINS
        value: https://veritensor.vercel.app
      - key: ADMIN_API_KEY
        generateValue: true
      - key: VERITENSOR_COMMIT_SECRET
        generateValue: true
